---
title: "Diagnostico Goiania Linhas"
author: "IPEA"
date: "23/08/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(sf)
library(dplyr)
library(mapview)
```

## Linhas antes da intervencao

Essas sao as principais linhas a serem substituidas com as intervencoes do BRT Norte Sul: 006, 007, 013

```{r linhas_antes}

gtfs_antes <- gtfstools::read_gtfs("../../data-raw/gtfs/goi/2019/gtfs_goi_rmtc_2019-10.zip")

# pegar servico principal
service <- gtfs_antes$calendar %>%
  filter(monday == 1 & tuesday == 1 &  wednesday == 1 &  thursday == 1 &  friday == 1)

# extrair linhas
routes_antes <- gtfs_antes$routes[route_id %like% "006|007|013|107|600|611"]$route_id # thenew lines

# pegar shapes
shapes_antes <- gtfs_antes$trips[route_id %in% routes_antes]$ shape_id %>% unique()
shapes_antes <- gtfstools::convert_shapes_to_sf(gtfs_antes) %>% filter(shape_id %in% shapes_antes) %>%
  mutate(route_id = substr(shape_id, 1, 3)) %>%
  group_by(route_id) %>%
  summarise() %>%
  st_cast("MULTILINESTRING")

ggplot()+
  

# visualizar esas linhas
mapview(shapes_antes, zcol = "route_id")

# select trips from 6am
trips_antes <- gtfs_antes$trips %>%
  filter(service_id %in% service$service_id) %>%
  filter(route_id %in% routes_antes)

st_antes <- gtfs_antes$stop_times %>%
  filter(trip_id %in% trips_antes$trip_id) %>%
  group_by(trip_id) %>%
  slice(1) %>%
  ungroup() %>%
  mutate(hora = lubridate::hms(arrival_time) %>% lubridate::hour()) %>%
  filter(hora == 6)

# calcular velocidade
speeds_antes <- gtfstools::get_trip_speed(gtfs_antes, trip_id = st_antes$trip_id)

```




```{r linhas_depois}

gtfs_depois <- gtfstools::read_gtfs("../../data/avaliacao_intervencoes/goi/gtfs_goi_rmtc_2019-10_depois.zip")

# extrair linhas
routes_depois <- gtfs_depois$routes[route_id %like% "BRT_006|BRT_007|BRT_013"]$route_id # thenew lines

# pegar shapes
shapes_depois <- gtfs_depois$trips[route_id %in% routes_depois]$ shape_id %>% unique()
shapes_depois <- gtfstools::convert_shapes_to_sf(gtfs_depois) %>% filter(shape_id %in% shapes_depois)

# visualizar esas linhas
mapview(shapes_depois, zcol = "shape_id")


# select trips from 6am
trips_depois <- gtfs_depois$trips %>%
  filter(service_id %in% service$service_id) %>%
  filter(route_id %in% routes_depois)

st_depois <- gtfs_depois$stop_times %>%
  filter(trip_id %in% trips_depois$trip_id) %>%
  group_by(trip_id) %>%
  slice(1) %>%
  ungroup() %>%
  mutate(hora = lubridate::hms(arrival_time) %>% lubridate::hour()) %>%
  filter(hora == 6)

# calcular velocidade
speeds_depois <- gtfstools::get_trip_speed(gtfs_depois, trip_id = st_depois$trip_id)


gtfstools::get_trip_geometry(gtfs_depois, trip_id = st_depois$trip_id)

```

Juntar os dois:

```{r linhas_juntas}

shapes_juntos <- rbind(
  shapes_antes <- shapes_antes %>% mutate(tipo = "antes"),
  shapes_depois <- shapes_depois %>% mutate(tipo = "depois")
)

mapview(shapes_juntos, zcol = "tipo")


```

